# STATUS: NOT RUNNABLE YET. This file imports tribunal.py, which is not
# published in this repository. It is kept here as a declaration of work in
# progress, not as a working demo. See README section 4.
#!/usr/bin/env python
"""demo_synthetic.py — runs the Judge on 100% fabricated data.

No real market data anywhere in this file. Every number is generated by
numpy's random generator with a fixed seed, purely to demonstrate the
mechanics: purge/embargo, CPCV fold construction, and a champion-vs-
challenger duel.

Run: python demo_synthetic.py
"""
import numpy as np
import pandas as pd

from tribunal import Judge, ModelCombined, ModelRandom, prepare_target


def make_synthetic_data(n_rows=5000, seed=42):
    rng = np.random.default_rng(seed)

    # Fabricated, evenly-spaced time intervals -- NOT real market timestamps.
    ts_start = np.arange(n_rows) * 60_000  # one row every simulated minute
    ts_end = ts_start + rng.integers(30_000, 90_000, size=n_rows)

    # Fabricated feature columns with a deliberately weak, made-up relationship
    # to the target, just so ModelCombined has something non-trivial to find.
    feature_a = rng.normal(size=n_rows)
    feature_b = rng.normal(size=n_rows)
    noise = rng.normal(size=n_rows)

    signal = 0.15 * feature_a - 0.05 * feature_b + noise
    target = (signal > np.quantile(signal, 0.7)).astype(int)  # fabricated binary label

    return pd.DataFrame({
        "ts_start": ts_start,
        "ts_end": ts_end,
        "feature_a": feature_a,
        "feature_b": feature_b,
        "target": target,
    })


def main():
    df = make_synthetic_data()
    print(f"Synthetic dataset: {len(df)} rows, target positive rate = {df['target'].mean():.3f}")

    judge = Judge(horizon_ms=120 * 60_000, embargo_ms=60 * 60_000, seed=0)

    champion = ModelRandom(seed=1)
    challenger = ModelCombined(features=["feature_a", "feature_b"], directions=[1.0, -1.0])

    result = judge.duel(
        df, champion, challenger,
        target_col="target",
        protocol="cpcv", n_groups=8, k_test=2,
    )

    print(f"\nVerdict: {result['verdict']}")
    print(f"Folds evaluated: {result['n_fold']}")
    print(f"Challenger won: {result['challenger_wins']}/{result['n_fold']} folds")
    print(f"Median delta AUC: {result['median_delta_auc']}")
    print(f"Sign-test p-value: {result['p_sign']}")


if __name__ == "__main__":
    main()
